# Generated by Django 3.0.6 on 2020-06-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sender', models.CharField(max_length=30)),
                ('Reciever', models.CharField(max_length=30)),
                ('Credit', models.IntegerField()),
                ('Time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='credit',
            field=models.IntegerField(),
        ),
    ]
