# Generated by Django 3.0.6 on 2020-06-05 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200605_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction_history',
            name='Credit',
        ),
        migrations.RemoveField(
            model_name='transaction_history',
            name='Reciever',
        ),
        migrations.RemoveField(
            model_name='transaction_history',
            name='Time',
        ),
    ]
