# Generated by Django 3.0.6 on 2020-06-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200605_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_history',
            name='Credit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction_history',
            name='Reciever',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transaction_history',
            name='Time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
