# Generated by Django 3.0.6 on 2020-06-05 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200605_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction_history',
            old_name='Reciever',
            new_name='Rec',
        ),
    ]
